dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
  - '13'

os:
  - linux

services:
  - xvfb

install:
  - npm install --no-progress

script:
  - npm run prettier:check
  - npm run lint
  - npm run test:ci
  - npm run lib:build
  - npm run example:build:prod
  - npm run compodoc:build
