dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
  - '13'

os:
  - linux

services:
  - xvfb

cache:
  directories:
    - ./node_modules

install:
  - npm install --no-progress
script:
  - npm run lib:build
  - npm run test:ci
  - npm run example:build:prod
  - npm run compodoc:build
